-- MySQL Script generated by MySQL Workbench
-- Mon Jul 10 23:14:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iras_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iras_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iras_db` DEFAULT CHARACTER SET utf8 ;
USE `iras_db` ;

-- -----------------------------------------------------
-- Table `iras_db`.`interviewee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iras_db`.`interviewee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `origin_text` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT '原始信息提取',
  `work_years` INT NULL,
  `education` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT '学历信息',
  `birth` DATE NULL COMMENT '年龄信息',
  `telephone` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT '电话',
  `gender` INT NULL COMMENT '性别，1代表男，2代表女',
  `native_place` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT '籍贯',
  `school` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT '毕业院校',
  `age` INT NULL,
  `political_status` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `file_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iras_db`.`experience`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iras_db`.`experience` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT '经历名称',
  `info` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT '工作内容',
  `company` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT '工作单位',
  `time` INT NULL,
  `interviewee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_experience_interviewee_idx` (`interviewee_id` ASC) VISIBLE,
  CONSTRAINT `fk_experience_interviewee`
    FOREIGN KEY (`interviewee_id`)
    REFERENCES `iras_db`.`interviewee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iras_db`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iras_db`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `time` INT NULL,
  `resp` TEXT NULL,
  `interviewee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_project_interviewee1_idx` (`interviewee_id` ASC) VISIBLE,
  CONSTRAINT `fk_project_interviewee1`
    FOREIGN KEY (`interviewee_id`)
    REFERENCES `iras_db`.`interviewee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iras_db`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iras_db`.`position` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT '工作名称',
  `work_year` INT NULL,
  `education` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL COMMENT '学历',
  `file_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  `origin_text` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iras_db`.`match_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iras_db`.`match_position` (
  `position_id` INT NOT NULL,
  `interviewee_id` INT NOT NULL,
  PRIMARY KEY (`position_id`, `interviewee_id`),
  INDEX `fk_position_has_interviewee_interviewee1_idx` (`interviewee_id` ASC) VISIBLE,
  INDEX `fk_position_has_interviewee_position1_idx` (`position_id` ASC) VISIBLE,
  CONSTRAINT `fk_position_has_interviewee_position1`
    FOREIGN KEY (`position_id`)
    REFERENCES `iras_db`.`position` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_position_has_interviewee_interviewee1`
    FOREIGN KEY (`interviewee_id`)
    REFERENCES `iras_db`.`interviewee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
