# Generated by Django 3.2.16 on 2023-07-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('origin_text', models.TextField(blank=True, db_collation='utf8mb3_bin', null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('work_years', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('ideal_pos', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('school', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('native_place', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('political_status', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('file_name', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
            ],
            options={
                'db_table': 'interviewee',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('work_year', models.IntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('file_name', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('origin_text', models.TextField(blank=True, db_collation='utf8mb3_bin', null=True)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('work_year', models.IntegerField(blank=True, null=True)),
                ('resp', models.TextField(blank=True, null=True)),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.interviewee')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('info', models.TextField(blank=True, db_collation='utf8mb3_bin', null=True)),
                ('company', models.CharField(blank=True, db_collation='utf8mb3_bin', max_length=45, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.interviewee')),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='MatchPosition',
            fields=[
                ('position', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='app.position')),
                ('interviewee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.interviewee')),
            ],
            options={
                'db_table': 'match_position',
                'unique_together': {('position', 'interviewee')},
            },
        ),
    ]
