# Generated by Django 3.2.16 on 2023-07-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='work_year',
        ),
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
