# Generated by Django 3.2.16 on 2023-07-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_interviewee_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewee',
            name='tags',
            field=models.TextField(blank=True, db_collation='utf8mb3_bin', null=True),
        ),
    ]
